// const successRequest = Promise.resolve({name:'Tom'});

// successRequest
// .then(data => {
//     console.log(data)
//     throw new Error('Unexpected error');
// })
// .catch(err=>{
//     console.error(err)
// });


// const failedRequest = Promise.reject(new Error('Fail'));

// failedRequest
// .then(data => {
//     console.log(data);
// })
// .catch(err => {
//     console.warn(err.message);
// })
// .then(data=>{
//     console.log(data)
// })

// fetch('https://api.com')
// .then(response =>{
//     return response.json();
// })
// .then(data=>console.log(data))
console.log(55)